name: Deploy on ZEIT

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@master
          with:
            node-version: 12.x 
        - run: npm build
